### ISSUE TITLE
Test HTTP errors

### ISSUE THREAD

**Issue by mykola-dev** [VictorAlbertos/Mockery#3]
Hi Victor!
How can we unit test http errors such '401' or time outs? It is not clear from documentation.
Thanks

**Comment by VictorAlbertos** [comment]
Hi @deviant-studio :)

I don't quite understand your question, but I'm going to try to answer it anyway.

Mockery provides a way to mock interfaces (plus it autogerates unit tests to test the annotated interfaces, but I think this is not related with the question). Usually you want to mock your networking layer with Mockery, in order to run your application with a mocked set of data. 

Now, you can configure the way Mockery behaves regarding server responses  setting specifics values for `delay` and `failurePercent` params when using `@Retrofit` or `@RxRetrofit` annotation (depending on the extension you were using).

What I do to use Mockery in my unit tests which depends on api calls is to subclass the interface and annotate it with another rate failure. It's quite easy and I can create as many subclasses-interfaces as needed to provide new configurations. For instance, RestApiFailure for failure assertions or RestApiSuccess to test success assertions.

An example:

``` java

@RxRetrofit
 interface GithubUsersApi { 
    //All the endpoints here 
}

@RxRetrofit(delay = 0, failurePercent = 0, variancePercentage = 0) 
interface ApiSuccess extends GithubUsersApi {

}

@RxRetrofit(delay = 0, failurePercent = 100, variancePercentage = 0) 
interface ApiFailure extends GithubUsersApi {

}

//Instantiate ApiSuccess to test success assertions.
GithubUsersApi githubUsersApi = new Mockery.Builder<ApiSuccess>().mock(ApiSuccess.class).build();

//Instantiate ApiFailure to test failure assertions.
GithubUsersApi githubUsersApi = new Mockery.Builder<ApiFailure>().mock(ApiFailure.class).build();

```

Does it answer your question?

**Comment by mykola-dev** [comment]
Yes, thanks.
My first thoughts about library usage was incorrect. What i'm trying to do is test retrofit observables behavior depending on http server response. Probably i should dig into interceptors and mocking http stack.

**Comment by VictorAlbertos** [comment]
Could you elaborate this a little more, please?

> test retrofit observables behavior depending on http server response

**Comment by mykola-dev** [comment]
Well, for example mocked server returns '401', in this case app triggers some retryWhen scenario, or uses okhttp authenticator (mocked). Than initial request should be retried. I'm just trying to test that flow.

**Comment by VictorAlbertos** [comment]
Ok, I see. Mockery doesn't support that kind of configuration. 

For that specific case, I think the best approach would be using Mockito or some other mocking framework to mock the method call ;)
