### ISSUE TITLE
Mock generic ResponseBody or Response

### ISSUE THREAD

**Issue by marco-manza** [VictorAlbertos/Mockery#8]
```
    @GET("api/v1/whatever")
    Observable<ResponseBody> getSomething();

```
```
    @GET("api/v1/whatever")
    Observable<Response> getSomething();
```

How can I mock such methods>

**Comment by VictorAlbertos** [comment]
It has been a while since I've used this library. So I can't tell you for sure, but maybe you can try to create your [own custom annotation](https://github.com/VictorAlbertos/Mockery#custom_annotations). Nevertheless, i think you should always specify the generic type working with Retrofit and Mockery.
